inherit_gem:
  rubocop-cache-ventures: rubocop.yml

Security:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Style/StringLiterals:
  Exclude:
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/*
    - config/initializers/assets.rb
    - config/puma.rb
    - Rakefile

Layout:
  Exclude:
    - config/environments/*.rb
